### ISSUE TITLE
Issue listener sometimes fails due to reading property on undefined

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-pack-issue#20]
Sometimes we see:

> Review listener _GitHub Issue Review Listener_ failed:
> 
> `Cannot read property 'data' of undefined`

Unfortunately, there are a lot of places in the code that look like `resp.data`.

**Comment by cdupuis** [comment]
Found the part in the logs that triggered this and fixed the usage of `response.data` in the catch blocks.
